### ISSUE TITLE
Error: The given key '' was not present in the dictionary.

### ISSUE THREAD

**Issue by ByFernanz** [rudism/Ficdown#6]
When using ficdown by the command line I get the following error when it is "Parsing story ...":

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key '' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Ficdown.Parser.Player.GameTraverser.ProcessState(StateQueueItem currentState) in /home/rudism/source/Ficdown/Ficdown.Parser/Player/GameTraverser.cs:line 147
   at Ficdown.Parser.Player.GameTraverser.Enumerate() in /home/rudism/source/Ficdown/Ficdown.Parser/Player/GameTraverser.cs:line 66
   at Ficdown.Parser.FicdownParser.ParseStory(String storyText) in /home/rudism/source/Ficdown/Ficdown.Parser/FicDownParser.cs:line 37
   at Ficdown.Console.Program.Main(String[] args) in /home/rudism/source/Ficdown/Ficdown.Console/Program.cs:line 136

---
I do not understand what the error refers to.

**Comment by ByFernanz** [comment]
Upps I'm sorry. This error occurs when this happens: [hello people] (?) When no variable is being evaluated.
